packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Next
  next: ^15.2.4
  # Dev tooling
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.15
  typescript: ^5.8.2
  convex: ^1.27.0
  "@types/node": ^22.13.11
  
  # Shared UI dependencies
  class-variance-authority: ^0.7.1
  cmdk: ^1.1.1
  lucide-react: ^0.553.0
  next-themes: ^0.4.6
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  clsx: ^2.1.1

  zod: ^3.24.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
