packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  next: 16.1.1

  "@types/node": "^22.13.11"
  "@eslint/js": ^9.38.0
  eslint: ^9.38.0
  prettier: ^3.6.2

  tailwindcss: ^4.1.16
  "@tailwindcss/postcss": ^4.1.16
  typescript: ^5.8.2

  zod: ^3.24.2

catalogs:
  react19:
    react: 19.2.1
    react-dom: 19.2.1
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
