packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.38.0
  '@hookform/resolvers': ^5.2.2
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.27.1
  '@types/node': ^22.13.11
  arktype: ^2.1.29
  class-variance-authority: ^0.7.1
  convex: ^1.27.0
  date-fns: ^4.1.0
  date-fns-tz: ^3.2.0
  embla-carousel-react: ^8.6.0
  eslint: ^9.38.0
  input-otp: ^1.4.2
  lucide-react: ^0.556.0
  next: 16.1.1
  next-themes: ^0.4.6
  prettier: ^3.6.2
  react-day-picker: ^9.13.0
  react-hook-form: ^7.68.0
  react-resizable-panels: ^3.0.6
  recharts: 2.15.4
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.16
  typescript: ^5.8.2
  vaul: ^1.1.2
  zod: ^3.24.2

catalogs:
  react19:
    '@types/react': 19.2.3
    '@types/react-dom': 19.2.3
    react: 19.2.3
    react-dom: 19.2.3
    react-is: 19.2.3

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
