packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  #Next
  next: ^15.2.6

  # Dev tooling
  "@types/node": "^22.13.11"
  "@eslint/js": ^9.38.0
  eslint: ^9.38.0
  prettier: ^3.6.2

  tailwindcss: ^4.1.16
  "@tailwindcss/postcss": ^4.1.16
  typescript: ^5.8.2

  # Misc
  zod: ^3.24.2

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
