/**
 * Test User Constants
 *
 * These are the WorkOS user IDs for test accounts.
 * Used for both unit tests (convex-test) and E2E tests.
 *
 * User roles:
 * - SITE_ADMIN: Has global admin access to all workspaces
 * - SITE_COACH: Site-level coach role (can be assigned to projects)
 * - WORKSPACE_ADMIN: Admin of a specific workspace
 * - PROJECT_MEMBER: Regular member assigned to a project
 * - UNASSIGNED_USER: Authenticated user with no workspace/project assignments
 */

// WorkOS User IDs from test environment
export const TEST_USERS = {
  /**
   * Site Admin - has global admin privileges
   * Email: admin.test@amaxaimpact.org
   */
  SITE_ADMIN: {
    id: "user_01KEYZVBEHVT7H0NKMK3A3G10C",
    email: "admin.test@amaxaimpact.org",
    name: "Site Admin",
  },

  /**
   * Site Coach - can be assigned as coach to projects
   * Email: coach.test@test.amaxaimpact.org
   */
  SITE_COACH: {
    id: "user_01KEYZYZFW81C7P5JJKK0S3KD0",
    email: "coach.test@test.amaxaimpact.org",
    name: "Site Coach",
  },

  /**
   * Workspace Admin - admin of a test workspace
   * Email: workspace-admin.test@test.amaxaimpact.org
   */
  WORKSPACE_ADMIN: {
    id: "user_01KFC1ERNZ4T5PCY3MQ8AZ9QRJ",
    email: "workspace-admin.test@test.amaxaimpact.org",
    name: "Workspace Admin",
  },

  /**
   * Project Member - regular member assigned to a project
   * Email: member.test@test.amaxaimpact.org
   */
  PROJECT_MEMBER: {
    id: "user_01KEZ02VF82SSCN8P7FA8XRTGJ",
    email: "member.test@test.amaxaimpact.org",
    name: "Project Member",
  },

  /**
   * Unassigned User - authenticated but no workspace/project access
   * Email: user.test@test.amaxaimpact.org
   */
  UNASSIGNED_USER: {
    id: "user_01KEZ03RBXD8VJ21089B29EQ24",
    email: "user.test@test.amaxaimpact.org",
    name: "Unassigned User",
  },
} as const;

// Type for test user keys
export type TestUserKey = keyof typeof TEST_USERS;

// Type for test user data
export type TestUser = (typeof TEST_USERS)[TestUserKey];

/**
 * Get a test user by key
 */
export function getTestUser(key: TestUserKey): TestUser {
  return TEST_USERS[key];
}

/**
 * Create identity object for convex-test withIdentity
 * This is the format expected by convex-test
 */
export function createIdentity(user: TestUser) {
  return {
    subject: user.id,
    email: user.email,
    name: user.name,
    // These are auto-generated by convex-test if not provided,
    // but we set them for consistency
    issuer: "https://test.amaxaimpact.org",
    tokenIdentifier: `https://test.amaxaimpact.org|${user.id}`,
  };
}

/**
 * Test workspace constants
 */
export const TEST_WORKSPACE = {
  slug: "e2e-test-workspace",
  name: "E2E Test Workspace",
} as const;

/**
 * Test project constants
 */
export const TEST_PROJECT = {
  name: "E2E Test Project",
  description: "Project for automated testing",
} as const;
